#
#   Makefile.fpc for Free Pascal Runtime Library
#

[package]
name=rtl
version=3.0.2

[target]
dirs_linux=linux

[install]
fpcpackage=y
createpackagefpc=y

[default]
fpcdir=..

[rules]
.NOTPARALLEL:
